### ISSUE TITLE
One of the USB 2.0 ports does not work with this build

### ISSUE THREAD

**Issue by lccreech** [riptidewave93/rk3328-debian#1]
The USB port works with friendly's "official" Ubuntu 20.04.1 LTS (GNU/Linux 5.15.53 aarch64) load.
I snatched their device tree table and it does have many differences. Theirs is also a trusted boot load which complicates things and no visible kernel config file. Modding the build.sh file for linux-5.15.y was the easy part the, .config and the dtb files will take some time.
I've attached a dump of their dtb.

One other issue that isn't much of a concern. That is the host build machine. Mine is Ubuntu 20.04 LTS x86_64. I found that snapd loopX mounts interfere with the build. I don't like snaps anyway and removed them. That fixed the the failed filesystem builds.

Other than those 2 things it worked great. I would like to see in the future the process of making a trusted boot and get the one OTG USB port working in the various otg modes.

[dtb.txt](https://github.com/riptidewave93/rk3328-debian/files/9238729/dtb.txt)

**Comment by riptidewave93** [comment]
@lccreech can you share what specific board you have, and which specific port? I probably am just missing something basic in the device tree.

**Comment by lccreech** [comment]
You can actually see it in the dtb.txt I supplied. It's the 2GB NanoPi
Neo3. On its 8 pin USB header, the inner one works, the outer one, with
your build not so much. Though it does work with Ubuntu 20.04 - Linux
5.15.y built from Friendly. They unfortunately do not supply the source
code or the dot config and have implemented the Secure Trusted Boot with
the Arm Trusted Firmware. Though I was able to pull the DTB out of  /proc.
It would match their Linux sources. It does not match what your sources
have. There are many more differences between the 2 than what I  normally
would have expected. But you have done some really good work getting it
this far without their help. There are a few more kernel modules I need
for  USB OTG support, and not built in since I need to load them with
parameters and unload them at will. This is for my Tesla USB project,
instead of using a raspberry pi zero..

**Comment by lccreech** [comment]
Chris,

I got it working, the usb port is now  working. I've attached my changes so
you can see what I added.
Feel free to use or commit what you see fit. I'm still working on
overlay/kernel/arch/arm64/configs/rk3328_defconfig to suit my needs.

Have a great weekend.
Larry

**Comment by riptidewave93** [comment]
Hwy @lccreech since this is github, the attachment was not included. If you can, please just send the diff. :)

**Comment by lccreech** [comment]
Chris,
a lot of time has passed since I last worked on that, including my
development computer, but this is what I still have from my work on the
device tree. From looking at it now it probably should be applied to the
uboot code as well.

***@***.***:~/rk3328-debian/BuildEnv/git# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   ../../build.sh
modified:
../../overlay/kernel/arch/arm64/boot/dts/rockchip/rk3328-nanopi-neo3.dts
modified:   ../../overlay/kernel/arch/arm64/configs/rk3328_defconfig

no changes added to commit (use "git add" and/or "git commit -a")
***@***.***:~/rk3328-debian/BuildEnv/git# tar zcf changes.tar.gz
../../build.sh
../../overlay/kernel/arch/arm64/boot/dts/rockchip/rk3328-nanopi-neo3.dts
../../overlay/kernel/arch/arm64/configs/rk3328_defconfig
tar: Removing leading `../../' from member names
tar: Removing leading `../../' from hard link targets
***@***.***:~/rk3328-debian/BuildEnv/git#

**Comment by riptidewave93** [comment]
Hey @lccreech, I'm currently working on a large refactor and update to this repo, and I will do more testing on the neo3 to ensure USB compatibility on all ports before merging it into main. You can look at my dev branch at https://github.com/riptidewave93/rk3328-debian/tree/blakec/docker if you are curious as to the changes.

**Comment by riptidewave93** [comment]
I have verified the header ports (2x usb) are working as expected with this refactor. As for the host port, that can be done with the right kernel modules being loaded http://trac.gateworks.com/wiki/linux/OTG
